# To build the entire stack run 'make run'

services:
  cache:
    environment:
      GIN_MODE: release
    networks:
      - cache
      - ingress

  redis:
    volumes:
      - ./data/redis:/data
    networks:
      - cache

networks:
  ingress:
    name: ingress
    external: true
  cache:
    name: cache
