# To build the entire stack run 'make run'

services:
  cache:
    environment:
      LOG_LEVEL: DEBUG
      KEMAL_ENV: development
      CRYSTAL_ENV: development
    networks:
      - cache
  
  redis:
    networks:
      - cache

networks:
  cache:
    name: cache
