# To build the entire stack run 'make run'

services:
  redis:
    container_name: redis
    image: redis:alpine3.16
    ports:
      - 6379:6379
    restart: unless-stopped
    command:
      [
        "redis-server",
        "--maxmemory",
        "1gb",
        "--maxmemory-policy",
        "allkeys-lru"
      ]
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  cache:
    container_name: cache
    restart: unless-stopped
    build:
      context: ./src/cache
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    environment:
      SENTRY_DSN: ${SENTRY_DSN:-}
      SENTRY_ENVIRONMENT: ${SENTRY_ENVIRONMENT:-}
      SENTRY_RELEASE: ${SENTRY_RELEASE:-cache@local}
      SENTRY_TRACE_RATE: ${SENTRY_TRACE_RATE:-1.0}
    depends_on:
      - redis
