#!/bin/bash

set -e

# COLORS
OFF='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'

# set the working directory to the root of the project
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

# check to ensure both crystal and shards are installed
if ! [ -x "$(command -v crystal)" ]; then
  echo -e "❌ ${RED}Error${OFF}: crystal is not installed"
  echo "Please install crystal via crenv -> https://github.com/crenv/crenv"
  exit 1
fi

if ! [ -x "$(command -v shards)" ]; then
  echo -e "❌ ${RED}Error${OFF}: shards is not installed"
  echo "Please install crystal (comes with shards) via crenv -> https://github.com/crenv/crenv"
  exit 1
fi

script/preinstall

SHARDS_CACHE_PATH="$DIR/.cache/shards" shards install --frozen $@

script/postinstall
