#!/bin/bash

set -e

# set the working directory to the root of the project
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

mkdir -p "$DIR/.cache/shards"

SHARDS_CACHE_PATH="$DIR/.cache/shards" shards run --release
