#!/bin/bash

set -euo pipefail

source script/env "$@"

# enter the project dir
echo -e "${BLUE}Entering cache directory...${OFF}"
cd "$CACHE_GO_DIR"

# run the tests
echo -e "${BLUE}Running tests...${OFF}"
if go test -mod=vendor -v -cover -race -count 3 ./...; then
    echo -e "${GREEN}✅ All tests passed!${OFF}"
else
    echo -e "${RED}❌ Tests failed!${OFF}"
    exit 1
fi
