#!/bin/bash

set -e

# set the working directory to the root of the project
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

script/preinstall

SHARDS_CACHE_PATH="$DIR/.cache/shards" shards update $@

script/postinstall
