name: acceptance

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  acceptance:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: acceptance tests
        run: script/acceptance
