name: config validation
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  json-yaml-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v2
        with:
          comment: "true"
          json_schema: ".github/schema/schema.json"
          base_dir: config/
