name: deploy-testing

on:
  pull_request:

permissions:
  contents: read

jobs:
  deploy-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.18

      - name: build
        run: |
         go mod download
         go mod verify
         GOOS=linux GOARCH=amd64 go build ./main.go

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

      - name: inject
        env:
          STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        run: |
          jq --arg connStr "$STORAGE_CONNECTION_STRING" '.Values.AzureWebJobsStorage = $connStr' local.settings.json > temp.json && mv temp.json local.settings.json  

      - name: Azure Functions Action
        uses: Azure/functions-action@v1.5.1
        with:
          app-name: tarkov-cache
          respect-funcignore: true
