name: test

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6
        with:
          persist-credentials: false

      - name: setup go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # pin@v6
        with:
          go-version-file: 'src/cache/go.mod'

      - name: bootstrap
        run: script/bootstrap

      - name: lint
        run: script/lint

      - name: build
        run: script/build
    
      - name: test
        run: script/test
